basic_settings:
  site_title: H.K. Vision
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/hk_vision_app_site_logo_small.png
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Portfolio'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Contact'
      url: '/contact'
    - title: 'About'
      url: '/about'

footer_settings:
  logo_image: /images/hk_vision_app_site_logo_small.png
  logo_width: 200
  footer_tagline: Vision though H.K.'s 👁️

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

# Search supported icons in https://fontawesome.com/icons?d=gallery
# For "<i class="fas fa-address-book"></i>" the link key should be "address-book_url"
social_settings:
  facebook_url: 'https://www.facebook.com/HKPhotography.ca'
  twitter_url: 'https://twitter.com/hossainkhan'
  instagram_url: 'https://www.instagram.com/hossainkhan/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  google-play_url: 'https://play.google.com/store/apps/details?id=com.hossainkhan.vision'
  vimeo_url: ''
  pinterest_url: ''
  medium_url: 'https://medium.com/@hossainkhan'
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''
  connectdevelop_url: 'https://hossainkhan.com/'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#F2784B'
  border_color: '#dddddd'
  overlay_background_color: '#F2784B'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: "
     <!-- Global site tag (gtag.js) - Google Analytics -->
     <script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-1394009-15\"></script>
     <script>
       window.dataLayer = window.dataLayer || [];
       function gtag(){dataLayer.push(arguments);}
       gtag('js', new Date());

       gtag('config', 'UA-1394009-15');
     </script>
"
  custom_styles: ""
  header_js: "
     <meta name=\"google-site-verification\" content=\"0MAnQ6XFeN-Hah3EtN9_R725LzS_MQz_2RRwGdjr3EI\" />
     <meta name=\"yandex-verification\" content=\"ae39ae8136c501e6\" />
     <meta name=\"theme-color\" content=\"#b93c0d\">
"
  footer_js: ""