# Validates JSON schema and data using Node module.
# https://github.com/ajv-validator/ajv-cli
name: Validate JSON on Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 12.x
      uses: actions/setup-node@v4
      with:
        node-version: 12.x
    - run: npm -v
    - run: npm install -g ajv-cli
    - run: ajv help
    - run: ajv validate -s photos-schema.json -d photos.json
